#!/bin/bash
nick="dragonbot"
server=chat.freenode.net
port=6667
chans=( "#nixheads" )
CHANNEL=
NAME=
BOTNICK=$nick
AUTHED() {
Owner="Dragonkeeper"
Trusted="fhsgjwlrhdkhvkvlk"
[ $SENDER == $Owner ] && {AuthedOnBot="Yes" ;sleep 10; AuthedOnBot="No"} || AuthedOnBot="No"
[ $SENDER == $Trusted ]  {AuthedOnBot="Yes" ;sleep 10; AuthedOnBot="No"} || AuthedOnBot="No"
}
filter() {
   filters["$1"]+="${@:2}"
}
run_filters() {
   for f in "${!filters[@]}"; do
      	[[ "$@" =~ $f ]] && {
		for func in ${filters[$f]}; do
		$func "${BASH_REMATCH[@]}"
		done
	}
   done
}
reload_filters() {
   for i in "${!filters[@]}"; do
      unset "filters[$i]"
   done
   for f in filters/*; do
      source "$f"
   done
}
builtin_filters()
{
   echo "active filters:";
   for f in "${!filters[@]}"; do
      printf "%-20s: %s\n" "$f" "${filters[$f]}"
   done
}
builtin_reload()
{
   wait
   send "QUIT :reloading"
   exec 3>&-
   exec "${bashbot_args[@]}"
}
builtin_list()
{
   echo -n "available commands: ${!builtin_commands[@]} "
   (cd commands; echo *;)
}
recv() { echo "< $@" >&2; }
send() { echo "> $@" >&2; printf "%s\r\n" "$@" >&3; }
export -f send
sleep 5
declare -A filters
export -f filter
reload_filters
declare -A builtin_commands
bashbot_args=("$0" "$@")
builtin_commands[reload]=builtin_reload
builtin_commands[filters]=builtin_filters
builtin_commands[list]=builtin_list
echo $$ >Dragon.pid
trap 'builtin_reload' SIGHUP
exec 3<>/dev/tcp/$server/$port || { echo "Could not connect"; exit 1; }
send "NICK $nick"
send "USER $nick 0 * :Dragon"
for chan in "${chans[@]}"; do
   send "JOIN :$chan"
done
export CHANNEL NAME BOTNICK

while read -r line; do
bashbotrecvfullline=${line}
export bashbotrecvfullline
   line=${line%%$'\r'}

   recv "$line"
   set -- $line
   case "$1" in
   :*)
      NAME=${1%%!*}
      NAME=${NAME#:}
      SENDER=$NAME
export -f AUTHED
      shift
      ;;
   esac
   case "$@" in
   "PING "*)
      send "PONG $2"
      continue
      ;;
   "PRIVMSG $nick :"*)
      CHANNEL=$NAME
      prefix="PRIVMSG $NAME "
      set -- "${3#:}" "${@:4}"
      ;;
   "PRIVMSG "*" :$nick: "*)
      CHANNEL=$2
      prefix="PRIVMSG $CHANNEL :$NAME"
      set -- "${@:4}"
      ;;
   "PRIVMSG "*" :"*)
      CHANNEL=$2
      run_filters "${3#:}" "${@:4}" | while IFS= read -r line; do
         send "PRIVMSG $CHANNEL :$line"
      done&
      continue
      ;;
   "KICK"*)
      for chan in "${chans[@]}"; do
	 send "JOIN :$chan"
      done&
      continue
	;;
   *)
      continue
      ;;
   esac
   cmd=${1##*/}
   shift
   case "$cmd" in
   reload)
      builtin_reload "$@"
      continue
      ;;
   esac
   if [ -n "${builtin_commands[$cmd]}" ]; then
      "${builtin_commands[$cmd]}" "$@"
      continue
   elif [ -x "commands/$cmd" ]; then
      "commands/$cmd" "$@"
   else
      "commands/replies"
   fi | while IFS= read -r line; do
      send "$prefix:$line"
   done&
done <&3
